language: ruby
sudo: false
cache: bundler
rvm:
  - ruby-head
  - 2.3.1
  - 2.2
  - 2.1
  - jruby
  - jruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby
    - rvm: jruby-head
    - rvm: ruby-head
env:
  global:
    - CODECLIMATE_REPO_TOKEN=70820b2c9137bc6411ae1a2e0c6861028c70ce373eec87ad46d9b7c14dce3401
    - JRUBY_OPTS='--dev -J-Xmx1024M'
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/556fa7e78f49c2f0016e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
